# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sch.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5.QtCore import QStringListModel  # Add this import
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(929, 691)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(22)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.predict_Button = QtWidgets.QPushButton(self.centralwidget)
        self.predict_Button.setGeometry(QtCore.QRect(610, 20, 301, 91))
        self.predict_Button.setObjectName("predict_Button")
        self.preview_picture = QtWidgets.QLabel(self.centralwidget)
        self.preview_picture.setGeometry(QtCore.QRect(610, 120, 301, 251))
        self.preview_picture.setObjectName("preview_picture")
        self.output_num = QtWidgets.QLabel(self.centralwidget)
        self.output_num.setGeometry(QtCore.QRect(610, 370, 301, 121))
        self.output_num.setObjectName("output_num")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 50, 221, 81))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 120, 221, 81))
        self.label_4.setObjectName("label_4")
        self.Train_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Train_Button.setGeometry(QtCore.QRect(100, 220, 251, 101))
        self.Train_Button.setObjectName("Train_Button")

        self.listView = QtWidgets.QListView(self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(80, 340, 321, 241))
        self.listView.setObjectName("listView")
        self.log_model = QStringListModel()
        self.listView.setModel(self.log_model)

        self.iter_num = QtWidgets.QTextEdit(self.centralwidget)
        self.iter_num.setGeometry(QtCore.QRect(250, 140, 321, 51))
        self.iter_num.setObjectName("iter_num")
        self.lr_num = QtWidgets.QTextEdit(self.centralwidget)
        self.lr_num.setGeometry(QtCore.QRect(250, 70, 321, 51))
        self.lr_num.setObjectName("lr_num")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.predict_Button.setText(_translate("MainWindow", "导入需要预测的素材"))
        self.preview_picture.setText(_translate("MainWindow", "素材预览preview"))
        self.output_num.setText(_translate("MainWindow", "预测结果为："))
        self.label_3.setText(_translate("MainWindow", "学习度梯度调整："))
        self.label_4.setText(_translate("MainWindow", "迭代次数调整："))
        self.Train_Button.setText(_translate("MainWindow", "训练模型"))
        self.iter_num.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Agency FB\'; font-size:22pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">输入迭代次数（整数）</p></body></html>"))
        self.lr_num.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Agency FB\'; font-size:22pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">请输入数字</p></body></html>"))
